#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Abort on any error
set -e

# Format code (and stage any formatting changes)
npm run format

# Run lint and type-check (they must pass)
# npm run lint
npm run type-check